AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Stack for Resume Scanner & Job Matcher
Parameters:
  Environment:
    Type: String
    Default: dev
  LabRoleArn:
    Type: String
    Description: ARN of the pre-existing LabRole

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "resume-matcher-userpool-${Environment}"
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: isInitialized
          AttributeDataType: String
          Mutable: true
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "resume-matcher-client-${Environment}"
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: false

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "resume-matcher-identitypool-${Environment}"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !Sub "cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "ResumeMatcher-${Environment}-UserPoolId"

  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "ResumeMatcher-${Environment}-UserPoolArn"

  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "ResumeMatcher-${Environment}-UserPoolClientId"
